### ISSUE TITLE
Installing node-hid-stream: too few arguments to function call, expected 3, have 2

### ISSUE THREAD

**Issue by mmihic96** [agirorn/node-hid-stream#32]
Error while installing node-hid:

gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../src/HID.cc:612:31: error: too few arguments to function call, expected 3, have 2
npm ERR! node::AtExit(deinitialize, 0);
npm ERR! ~~~~~~~~~~~~ ^
npm ERR! /Users/milosmihic/Library/Caches/node-gyp/16.13.0/include/node/node.h:913:18: note: 'AtExit' declared here
npm ERR! NODE_EXTERN void AtExit(Environment* env,
npm ERR! ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/HID/src/HID.o] Error 1

node version: 16.13.0
npm version: 8.1.0
os: macOS Monterey v12.0.1

**Comment by mmihic96** [comment]
I found a solution for the issue.

I noticed that node-hid-stream uses an old version of node-hid.

`npm shrinkwrap` resolved my issue. I changed `node-hid` version in the dependency tree for `node-hid-stream`.

https://nodejs.org/en/blog/npm/managing-node-js-dependencies-with-shrinkwrap/

**Comment by zivyuan** [comment]
> node-hid-stream

Which version do you use?

**Comment by mmihic96** [comment]
@zivyuan
node-hid-stream: 1.1.0
node-hid: 2.1.1

But, I solved it, the solution is in the previous comment.
