### ISSUE TITLE
Data limit from a barcode seems to be 64

### ISSUE THREAD

**Issue by ndrantotiana** [agirorn/node-hid-stream#5]
When I try to scan an AZTEC 2D code, I received at least 4 consecutive datas. Is it a mis-configuration of the scanner or just that the data is too long that it should be splited into 4 parts of 3 64characters and then the rest?

**Comment by agirorn** [comment]
I'm assuming you are using the KeyboardLines to get the content of the barcode from the scanner. If the barcode has the carrier return(newline) character in it I believe the that terminates read and emit that as on barcode event. the barcodes I have been working with do not have that character in them and I have been configuring the barcode readers to add that char at the end of each scan, hopefully, you can do that. If that is not the case then you might be able to configure the reader to either add a different character at the end of the scan, some char/token that you know you probably get in the barcodes like ^ and then we can change what KeboardLines uses to split the barcode/lines.

Maybe we could add a BarcodeReader class that could be improved to cover more of the edge cases of barcode reading.

**Comment by agirorn** [comment]
I'm closing this since it has not had any activity for a long time.

**Comment by agirorn** [comment]
I'm closing this since it has not had any activity for a long time.
