### ISSUE TITLE
 cannot open device

### ISSUE THREAD

**Issue by dimitrisal** [agirorn/node-hid-stream#7]
` var Keyboard = require('node-hid-stream').Keyboard;
    var keyboard = new Keyboard({ vendorId: 65535, productId: 53 });
     
    keyboard.on("data", function(data) {
      console.log(data); // easily consumed data format!
    });`

I am using the basic code only to read data from a scanner on windows 10 but i get this error :

C:\Users\Balkan_Med1\Desktop\scanner2\node_modules\node-hid-stream\node_modules\node-hid\nodehid.js:24
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

Error: cannot open device with vendor id 0xffff and product id 0x35
    at new HID (C:\Users\Balkan_Med1\Desktop\scanner2\node_modules\node-hid-stream\node_modules\node-hid\nodehid.js:24:17)
    at newHidDevice (C:\Users\Balkan_Med1\Desktop\scanner2\node_modules\node-hid-stream\lib\hidstream.js:55:10)
    at new Hidstream (C:\Users\Balkan_Med1\Desktop\scanner2\node_modules\node-hid-stream\lib\hidstream.js:21:19)
    at new KeyboardBase (C:\Users\Balkan_Med1\Desktop\scanner2\node_modules\node-hid-stream\lib\keyboard-base.js:9:19)
    at new Keyboard (C:\Users\Balkan_Med1\Desktop\scanner2\node_modules\node-hid-stream\lib\keyboard.js:9:5)
    at Object.<anonymous> (C:\Users\Balkan_Med1\Desktop\scanner2\index.js:3:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

**Comment by agirorn** [comment]
Sorry, but I have never used this on Windows. If the scanner is registering itself as a keyboard on Windows you may be unable to connect to it according to node-hid [windows notes](https://github.com/node-hid/node-hid#windows-notes). 

Potentially you could configure the scanner not to register itself as a keyboard but as a data stream device. If that does not work you could configure it to register is self as a serial device and read its data from the serial port and use https://serialport.io/ to read from the scanner.

**Comment by agirorn** [comment]
@dimitrisal do you think this could be related to #8?

I just released a new version and would really like to know if this is fixed in that version.

**Comment by dimitrisal** [comment]
@agirorn i doubt it is the same. That error is due to npm, maybe will work with yarn install or something while my error is due to the windows' drivers. Basically windows drivers reserve the device and I can't access it because it seems that is already open.

**Comment by agirorn** [comment]
I think we also experienced this issue with some scanners and could work around the problem by configuring the scanners by scanning the configuration barcodes that tell the scanner not to emulate a keyboard. Have you looked into that?

**Comment by dimitrisal** [comment]
I found a work around with an external software that basically changed the drivers of the scanner. I haven't looked at it since i found that solution. Can you explain to me how you made that configuration?

**Comment by agirorn** [comment]
It's been some time since I did this but I believe the procedure is like this.

For example on the Xenon 1900 scanner. Get the [manual](https://www.honeywellaidc.com/en/-/media/en/files-public/technical-publications/barcode-scanners/Xenon/NG2D-QS.pdf) and then scan the "Standard Product Defaults" barcode first to reset the scanner then scan then the "USB Serial" barcode. Then the scanner should not register itself as a keyboard anymore. You might need to unplug and plug in the scanner afterward just to be sure.

Then to have this `node-hid-stream` `KeyboardLines` work correctly you might also need to scan the "Add CR Suffix" to ensure the scanner adds a `<CR>` at the end of every scan to denote the end of the scan.
