### ISSUE TITLE
upgrade to node-hid@0.7.9

### ISSUE THREAD

**Issue by lumpov** [agirorn/node-hid-stream#8]
cannot install on node v10.16.0 npm v6.10.1

**Comment by agirorn** [comment]
- @lumpov are you suggesting I need to upgrade the node-hid dependency?
- Can you provide more information on what exactly the error is?
- It would be very helpful to get the error printed on the console when you ran `npm install node-hid-stream`.

**Comment by lemontea888** [comment]
windows 7 electron 4.2.6
node-hid is Build succeeded.
[ npm -save install node-hid --runtiom=electron --target=4.2.6 --dist-url=https://atom.io/download/electron --build-from-source --verbose ]

node-hid-stream is Build FAILED.
[ npm -save install node-hid-stream --runtiom=electron --target=4.2.6 --dist-url=https://atom.io/download/electron --build-from-source --verbose ]
--------------------------------------------------------------
"D:\Programming\Git\E_template\node_modules\node-hid-stream\node_modules\node-hid\build\binding.sln
" (default target) (1) ->
"D:\Programming\Git\E_template\node_modules\node-hid-stream\node_modules\node-hid\build\HID.vcxproj
.metaproj" (default target) (2) ->
"D:\Programming\Git\E_template\node_modules\node-hid-stream\node_modules\node-hid\build\HID.vcxproj
" (default target) (4) ->
(ClCompile target) ->
  d:\programming\git\e_template\node_modules\node-hid-stream\node_modules\node-hid\src\hid.cc(207):
 error C2661: 'v8::Function::NewInstance': ??????? 2 ?? [D:\Programming\Git\E_template\node_modules
\node-hid-stream\node_modules\node-hid\build\HID.vcxproj]

    7 Warning(s)
    1 Error(s)
-------------------------------------------------------------------------------------
 d:\programming\git\e_template\node_modules\node-hid-stream\node_modules\node-hid\src\hid.cc(207):
 error C2661: 'v8::Function::NewInstance': ??????? 2 ?? [D:\Programming\Git\E_template\node_modules
\node-hid-stream\node_modules\node-hid\build\HID.vcxproj]
---------------------------------------------------------------------------------------

**Comment by agirorn** [comment]
@lumpov and @lemontea888 thank you for the feedback. Would either of you like to make a pull request with the fixes required?

**Comment by agirorn** [comment]
@ragnese thanks for the PR.

This has now been released on [npm as version 1.1.0](https://www.npmjs.com/package/node-hid-stream).
